/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas.Vista;


import Seguridad.Controlador.clsBitacora;
import Ventas.Controlador.clsCotizacion;
import Seguridad.Controlador.clsUsuarioConectado;
import Ventas.Controlador.clsTienda;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author visitante
 */
public class frmConsultaCotizacionDetalle extends javax.swing.JInternalFrame {

    public void llenadoDeCombos() {
        /*EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        List<Empleado> empleados = empleadoDAO.select();
        cbox_empleado.addItem("Seleccione una opción");
        for (int i = 0; i < empleados.size(); i++) {
            cbox_empleado.addItem(empleados.get(i).getNombreEmpleado());
        } */
    }


    private DefaultTableModel modeloTabla;
    
    public frmConsultaCotizacionDetalle(int cotidSeleccionado) {
        initComponents();
        llenadoDeTablasCotizaciones(cotidSeleccionado);
        llenadoDeCombos();
    }

    int codigoAplicacion = 3005;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2CotizacionConsDet = new javax.swing.JLabel();
        lbusuCotizacionConsDet = new javax.swing.JLabel();
        jScrollPane1CotDetCons = new javax.swing.JScrollPane();
        jTable1CotDetCons = new javax.swing.JTable();
        jScrollPaneCotReg = new javax.swing.JScrollPane();
        tblCotConsDet = new javax.swing.JTable();
        lbCotDetCons = new javax.swing.JLabel();

        lb2CotizacionConsDet.setForeground(new java.awt.Color(204, 204, 204));
        lb2CotizacionConsDet.setText(".");

        jTable1CotDetCons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1CotDetCons.setViewportView(jTable1CotDetCons);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cotizaciones");
        setVisible(true);

        tblCotConsDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneCotReg.setViewportView(tblCotConsDet);

        lbCotDetCons.setText("Detalle de la Cotización:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPaneCotReg, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(lbCotDetCons)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lbCotDetCons)
                .addGap(33, 33, 33)
                .addComponent(jScrollPaneCotReg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void llenadoDeTablasCotizaciones(int cotidSeleccionado) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id Cotizacion");
        modelo.addColumn("Codigo Producto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Sub Total");
        clsCotizacion cotizacion = new clsCotizacion();
        List<clsCotizacion> listaCotizaciones = cotizacion.getListadoCotizacionesDetalle(cotidSeleccionado);
        tblCotConsDet.setModel(modelo);
        String[] dato = new String[5];
        for (int i = 0; i < listaCotizaciones.size(); i++) {
            dato[0] = Integer.toString(listaCotizaciones.get(i).getIdCot());
            dato[1] = Integer.toString(listaCotizaciones.get(i).getIdProducto());
            dato[2] = Double.toString(listaCotizaciones.get(i).getPrecioProducto());
            dato[3] = Integer.toString(listaCotizaciones.get(i).getCantidadProducto());
            dato[4] = Double.toString(listaCotizaciones.get(i).getTotalCot());
            
            modelo.addRow(dato);
        }              

                    

}
    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1CotDetCons;
    private javax.swing.JScrollPane jScrollPaneCotReg;
    private javax.swing.JTable jTable1CotDetCons;
    private javax.swing.JLabel lb2CotizacionConsDet;
    private javax.swing.JLabel lbCotDetCons;
    private javax.swing.JLabel lbusuCotizacionConsDet;
    private javax.swing.JTable tblCotConsDet;
    // End of variables declaration//GEN-END:variables


}