/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas.Vista;


import Seguridad.Controlador.clsBitacora;
import Ventas.Controlador.clsCotizacion;
import Seguridad.Controlador.clsUsuarioConectado;
import Ventas.Controlador.clsTienda;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author visitante
 */
public class frmConsultaCotizacion extends javax.swing.JInternalFrame {

    public void llenadoDeCombos() {
        /*EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        List<Empleado> empleados = empleadoDAO.select();
        cbox_empleado.addItem("Seleccione una opción");
        for (int i = 0; i < empleados.size(); i++) {
            cbox_empleado.addItem(empleados.get(i).getNombreEmpleado());
        } */
    }


    private DefaultTableModel modeloTabla;
    
    public frmConsultaCotizacion() {
        initComponents();
        llenadoDeTablasCotizaciones();
        llenadoDeCombos();
    }

    int codigoAplicacion = 3005;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2CotizacionCons = new javax.swing.JLabel();
        lbusuCotizacionCons = new javax.swing.JLabel();
        jScrollPane1CotCons = new javax.swing.JScrollPane();
        jTable1CotCons = new javax.swing.JTable();
        jScrollPaneCotReg = new javax.swing.JScrollPane();
        tblCotConsulta = new javax.swing.JTable();
        lbCotReg = new javax.swing.JLabel();
        btnVerDetalleCot = new javax.swing.JButton();
        btnPedidoCot = new javax.swing.JButton();
        lbInsCotReg = new javax.swing.JLabel();

        lb2CotizacionCons.setForeground(new java.awt.Color(204, 204, 204));
        lb2CotizacionCons.setText(".");

        jTable1CotCons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1CotCons.setViewportView(jTable1CotCons);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cotizaciones");
        setVisible(true);

        tblCotConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneCotReg.setViewportView(tblCotConsulta);

        lbCotReg.setText("Cotizaciones Registradas:");

        btnVerDetalleCot.setText("Ver Detalle");
        btnVerDetalleCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalleCotActionPerformed(evt);
            }
        });

        btnPedidoCot.setText("Realizar Pedido");
        btnPedidoCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoCotActionPerformed(evt);
            }
        });

        lbInsCotReg.setText("Haz clic en la cotización que quieras trabajar, luego presiona un botón:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(lbCotReg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbInsCotReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneCotReg, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVerDetalleCot)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPedidoCot)
                        .addGap(113, 113, 113))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCotReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lbInsCotReg)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCotReg, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnVerDetalleCot)
                        .addGap(66, 66, 66)
                        .addComponent(btnPedidoCot)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDetalleCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleCotActionPerformed
        // TODO add your handling code here:
// Crea una instancia de FrmConsultaCotizacionDetalle
                int filaSeleccionada = tblCotConsulta.getSelectedRow();
                int cotidSeleccionado = Integer.valueOf(tblCotConsulta.getValueAt(filaSeleccionada, 0).toString());
                frmConsultaCotizacionDetalle frmConsulta = new frmConsultaCotizacionDetalle(cotidSeleccionado);

                // Agrega el FrmConsultaCotizacionDetalle al JDesktopPane
                JDesktopPane desktopPane = getDesktopPane();
                desktopPane.add(frmConsulta);
                frmConsulta.setVisible(true);
                frmConsulta.toFront();
                int resultadoBitacora=0;
                    clsBitacora bitacoraRegistro = new clsBitacora();
                    resultadoBitacora = bitacoraRegistro.setIngresarBitacora(clsUsuarioConectado.getIdUsuario(),codigoAplicacion,"QRY"); 

    }//GEN-LAST:event_btnVerDetalleCotActionPerformed

    private void btnPedidoCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoCotActionPerformed
        // TODO add your handling code here:
                int filaSeleccionada = tblCotConsulta.getSelectedRow();
                int cotidSeleccionado = Integer.valueOf(tblCotConsulta.getValueAt(filaSeleccionada, 0).toString());
                clsCotizacion frmConsulta = new clsCotizacion();
                frmConsulta.RegistrarPedidoCot(cotidSeleccionado);
                frmConsulta.RegistrarPedidoCotDet(cotidSeleccionado);
                int resultadoBitacora=0;
                    clsBitacora bitacoraRegistro = new clsBitacora();
                    resultadoBitacora = bitacoraRegistro.setIngresarBitacora(clsUsuarioConectado.getIdUsuario(),codigoAplicacion,"INS"); 
    }//GEN-LAST:event_btnPedidoCotActionPerformed

     public void llenadoDeTablasCotizaciones() {
        DefaultTableModel modelo = new DefaultTableModel(){
            public boolean isCellEditable(int row, int column) {
                return false; // Desactivar la edición de las celdas
            }
        };
        modelo.addColumn("Id Cotizacion");
        modelo.addColumn("Id Cliente");
        modelo.addColumn("Id Vendedor");
        modelo.addColumn("Fecha");
        modelo.addColumn("Total");
        clsCotizacion cotizacion = new clsCotizacion();
        //VendedorDAO vendedorDAO = new VendedorDAO();
        List<clsCotizacion> listaCotizaciones = cotizacion.getListadoCotizaciones();
        tblCotConsulta.setModel(modelo);
        String[] dato = new String[5];
        for (int i = 0; i < listaCotizaciones.size(); i++) {
            dato[0] = Integer.toString(listaCotizaciones.get(i).getIdCot());
            dato[1] = Integer.toString(listaCotizaciones.get(i).getIdCliente());
            dato[2] = Integer.toString(listaCotizaciones.get(i).getIdVendedor());
            dato[3] = listaCotizaciones.get(i).getFechaCot();
            dato[4] = Double.toString(listaCotizaciones.get(i).getTotalCot());
            modelo.addRow(dato);
        }              

                    

}
    
public int obtenerCotidSeleccionado() {
    int filaSeleccionada = tblCotConsulta.getSelectedRow();
    int cotidSeleccionado = (int) tblCotConsulta.getValueAt(filaSeleccionada, 0);
    return cotidSeleccionado;
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedidoCot;
    private javax.swing.JButton btnVerDetalleCot;
    private javax.swing.JScrollPane jScrollPane1CotCons;
    private javax.swing.JScrollPane jScrollPaneCotReg;
    private javax.swing.JTable jTable1CotCons;
    private javax.swing.JLabel lb2CotizacionCons;
    private javax.swing.JLabel lbCotReg;
    private javax.swing.JLabel lbInsCotReg;
    private javax.swing.JLabel lbusuCotizacionCons;
    private javax.swing.JTable tblCotConsulta;
    // End of variables declaration//GEN-END:variables


}