/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


//Carlos Emanuel Hernandez Garcia
//9959-21-363
//Mantenimiento Vendedores
package Ventas.Vista;


import Seguridad.Controlador.clsBitacora;
import Ventas.Controlador.clsCotizacion;
import Seguridad.Controlador.clsUsuarioConectado;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author visitante
 */
public class frmCotizacion extends javax.swing.JInternalFrame {

    public void llenadoDeCombos() {
        /*EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        List<Empleado> empleados = empleadoDAO.select();
        cbox_empleado.addItem("Seleccione una opción");
        for (int i = 0; i < empleados.size(); i++) {
            cbox_empleado.addItem(empleados.get(i).getNombreEmpleado());
        } */
    }

   

//a
    


int codigoAplicacion = 3004;

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2Vendedores = new javax.swing.JLabel();
        lbusuVendedores = new javax.swing.JLabel();
        lbCodProdCot = new javax.swing.JLabel();
        lbCotActual = new javax.swing.JLabel();
        lbCantProdCot = new javax.swing.JLabel();
        lbTotalCot = new javax.swing.JLabel();
        txtTotalCot = new javax.swing.JTextField();
        btnAgregarCot = new javax.swing.JButton();
        txtCodProdCot = new javax.swing.JTextField();
        btnModificarCot = new javax.swing.JButton();
        txtCantProdCot = new javax.swing.JTextField();
        btnEliminarCot = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCotActual = new javax.swing.JTable();

        lb2Vendedores.setForeground(new java.awt.Color(204, 204, 204));
        lb2Vendedores.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento Vendedores");
        setVisible(true);

        lbCodProdCot.setText("Codigo del Producto:");

        lbCotActual.setText("Cotización Actual:");

        lbCantProdCot.setText("Cantidad del Producto:");

        lbTotalCot.setText("TOTAL DE LA COTIZACIÓN:");

        txtTotalCot.setEditable(false);

        btnAgregarCot.setText("Agregar");

        btnModificarCot.setText("Modificar");

        btnEliminarCot.setText("Eliminar");

        tblCotActual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", ""},
                {"", "", ""},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo Producto", "Cantidad", "SubTotal"
            }
        ));
        jScrollPane2.setViewportView(tblCotActual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 621, Short.MAX_VALUE)
                .addComponent(lbTotalCot)
                .addGap(18, 18, 18)
                .addComponent(txtTotalCot, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbCantProdCot)
                        .addComponent(lbCodProdCot))
                    .addComponent(btnAgregarCot))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificarCot)
                        .addGap(57, 57, 57)
                        .addComponent(btnEliminarCot))
                    .addComponent(txtCantProdCot, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodProdCot, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbCotActual)
                        .addGap(231, 231, 231))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbCotActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCodProdCot)
                            .addComponent(txtCodProdCot, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCantProdCot)
                            .addComponent(txtCantProdCot, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarCot)
                            .addComponent(btnModificarCot)
                            .addComponent(btnEliminarCot))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCot, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotalCot))
                .addGap(182, 182, 182))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCot;
    private javax.swing.JButton btnEliminarCot;
    private javax.swing.JButton btnModificarCot;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb2Vendedores;
    private javax.swing.JLabel lbCantProdCot;
    private javax.swing.JLabel lbCodProdCot;
    private javax.swing.JLabel lbCotActual;
    private javax.swing.JLabel lbTotalCot;
    private javax.swing.JLabel lbusuVendedores;
    private javax.swing.JTable tblCotActual;
    private javax.swing.JTextField txtCantProdCot;
    private javax.swing.JTextField txtCodProdCot;
    private javax.swing.JTextField txtTotalCot;
    // End of variables declaration//GEN-END:variables
}
